apiVersion: v1
kind: Service
metadata:
 name: mysql-headless
 namespace: expense1
spec:
 clusterIP: None  #this is called headless service
 selector:
   component: mysql
   purpose: db 
   project: expense 
 ports: 
 - protocol: TCP
   port: 3306
   targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
 name: mysql-headless
 namespace: expense1
spec:
 selector:
   component: mysql
   purpose: db 
   project: expense 
 ports: 
 - protocol: TCP
   port: 3306
   targetPort: 3306
   

