apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 891959/frontend:v.1.0
          ports:
        - containerPort: 8080
      volumeMounts:
      - name: config
        mountPath: "/etc/nginx/nginx.conf"
        subPath: nginx.conf
    volumes:
         # You set volumes at the Pod level, then mount them into containers inside that Pod
    - name: config
      configMap:
         # Provide the name of the ConfigMap you want to mount.
        name: frontend
         