apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense1
spec:
  type: 
   LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080