kind: Pod
apiVersion: v1
metadata: 
 name: env-example
 labels:
  type: frontend
spec:
 containers:
 - name: nginx
   image: nginx
   env: 
    - name: course
      value: devops
    - name: name
      value: yash
