apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    tier: frontend
    project: expense
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      project: expense
  template:
    metadata:
      labels:
        tier: frontend
        project: expense
    spec:
      containers:
      - name: frontend
        image: 891959/frontend:v.1.0
        ports:
        - containerPort: 8080
        volumeMounts:
         name: config
         mountPath: "/etc/nginx/nginx.conf"
         subPath: "nginx.conf"
         readOnly: true
      volumes:
      - name: config
        configMap:
         name: frontend
          