apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc  # this should be match with the storage class name that we created
  resources:
    requests:
      storage: 4Gi