apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: expense1
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: 891959/mysql:v.1.0
          ports:
          - containerPort: 3306